name: Build & Release GoPeerFlix

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build Executables
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            name: gopeerflix-linux-amd64
          - goos: linux
            goarch: arm64
            name: gopeerflix-linux-arm64
          - goos: darwin
            goarch: amd64
            name: gopeerflix-macos-amd64
          - goos: darwin
            goarch: arm64
            name: gopeerflix-macos-arm64
          - goos: windows
            goarch: amd64
            name: gopeerflix-windows.exe
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
          cache: true

      - name: Build
        run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} CGO_ENABLED=0 go build -ldflags="-s -w" -o ${{ matrix.name }} ./cmd

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: gopeerflix-binaries
          path: |
            gopeerflix-linux-amd64
            gopeerflix-linux-arm64
            gopeerflix-macos-amd64
            gopeerflix-macos-arm64
            gopeerflix-windows.exe

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: gopeerflix-binaries
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
        with:
          files: |
            gopeerflix-linux-amd64
            gopeerflix-linux-arm64
            gopeerflix-macos-amd64
            gopeerflix-macos-arm64
            gopeerflix-windows.exe
