name: Build & Release GoPeerFlix

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    name: Build Executables
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            name: gopeerflix-linux-amd64
          - goos: linux
            goarch: arm64
            name: gopeerflix-linux-arm64
          - goos: darwin
            goarch: amd64
            name: gopeerflix-macos-amd64
          - goos: darwin
            goarch: arm64
            name: gopeerflix-macos-arm64
          - goos: windows
            goarch: amd64
            name: gopeerflix-windows.exe
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: 1.23
          cache: true

      - name: Build
        run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} CGO_ENABLED=0 go build -ldflags="-s -w" -o ${{ matrix.name }} ./cmd

      - name: Upload binary
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.name }}

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v8
        with:
          pattern: gopeerflix-*
          path: .
          merge-multiple: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            gopeerflix-linux-amd64
            gopeerflix-linux-arm64
            gopeerflix-macos-amd64
            gopeerflix-macos-arm64
            gopeerflix-windows.exe
